name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build Docker image
      # run: docker build . --file Dockerfile --tag dad-jokes:latest
      run: docker build -t dad-jokes .
#    - name: Run Docker container
#      run: docker run -d -p 8080:8080 dad-jokes
    - name: Test python app
      run: pytest -v
